### PR TITLE
Fix provider exception

### PR DESCRIPTION
**Pull request by metimus**

### CODE REVIEW

**Comment by marshallpierce** [comment]
Even with this fix, though, we're still not following the javadoc, which says the provider can't be used until the injector is created. :( https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/Binder.html#getProvider-java.lang.Class-

**Comment by metimus** [comment]
It also says, that it will throw IllegalStateException if it is called before time, that doesn't happen, but if you don't like it that way, there is another way too, using requestInjection, take a look at next commit.

It is not production ready code, some other changes needed (it is not very good to bind MetricRegistry), so there probably internal additional interface is needed, but I only demonstrate that all tests are working with that approach too and no Provider is used.

**Comment by marshallpierce** [comment]
That doesn't work either. See the latest on my branch -- once the injector setup starts binding types that actually use the listeners, it fails because the registry hasn't been injected yet.

**Comment by metimus** [comment]
I found that there is open bug/improvement in guice task list regarding injection in type listeners. There is a way to make it work (like lazy initialization inside interceptor on first intercept with memoized metric supplier), but it contains too much changes, and it will change behavior, like metric definition not at start etc.  So thank you for your time, I will close pull requests.

Also if interceptor is binded using bindInterceptor from guice module, it is possible to use getProvider.

**Comment by marshallpierce** [comment]
Bummer, that's too bad -- link to the guice bug so they can see this could have used that feature! :)

**Pull request closed without merging**
