### PR TITLE
Type level annotation support implemented

### PR DESCRIPTION
**Pull request by htimur**
Reimplemented type level annotation support with better abstraction and extensibility.

### CODE REVIEW

**Comment by htimur** [comment]
@marshallpierce I updated the pull request, please review.

**Comment by marshallpierce** [comment]
OK, thanks. I'll check this out in the next couple of days.

**Comment by marshallpierce** [comment]
This looks great, thanks! I'll make a few minor wording tweaks and release a new version with this feature. Also, I'll remove the `@author` javadoc -- the rest of the project doesn't use them and your contribution will be quite visible in git history. :)

**Comment by marshallpierce** [comment]
3.2.0 has been released.

**Comment by htimur** [comment]
Awesome thanks!

**Pull request merged**
